# Generated by Django 4.2.7 on 2024-01-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Repair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_of_repair", models.TextField(max_length=500)),
                ("costs_incl_VAT", models.CharField(max_length=30)),
                ("VAT_percentage", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("other_information", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="External_Partie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("type_of_company", models.CharField(max_length=100)),
                ("last_name_contact", models.CharField(max_length=100)),
                ("address_company", models.CharField(max_length=100)),
                ("phone_number_company", models.CharField(max_length=15)),
                ("other_information_company", models.TextField(max_length=500)),
                (
                    "first_name_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VVE_ADMINISTRATION.resident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_board_member",
                        to="VVE_ADMINISTRATION.resident",
                    ),
                ),
                (
                    "first_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_name_board_member",
                        to="VVE_ADMINISTRATION.resident",
                    ),
                ),
                (
                    "last_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_name_board_member",
                        to="VVE_ADMINISTRATION.resident",
                    ),
                ),
                (
                    "other_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_information_board_member",
                        to="VVE_ADMINISTRATION.resident",
                    ),
                ),
                (
                    "phone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phonenumber_name_board_member",
                        to="VVE_ADMINISTRATION.resident",
                    ),
                ),
            ],
        ),
    ]
