# Generated by Django 4.2.7 on 2024-01-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("VVE_ADMINISTRATION", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmember",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="last_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="VVE_ADMINISTRATION.resident",
            ),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="other_information",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
