# Generated by Django 4.2.7 on 2024-01-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VVE_ADMINISTRATION", "0004_alter_boardmember_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="external_partie",
            name="first_name_contact",
            field=models.CharField(max_length=100),
        ),
    ]
