# Generated by Django 4.2.7 on 2024-01-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VVE_ADMINISTRATION", "0005_alter_external_partie_first_name_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="external_partie",
            name="other_information_company",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
