# Generated by Django 4.2.7 on 2024-01-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VVE_ADMINISTRATION", "0006_alter_external_partie_other_information_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmember",
            name="other_information",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="resident",
            name="other_information",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
